[package]
name = "xmake-example"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4.0"
log4rs = { version = "1.2", features = ["toml", "json_encoder"] }
config = "0.13"
confy = "0.5.1"
once_cell = { version = "1.16" }
bytes = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.8"
serde_yaml = "0.8"
tokio = { version = "1.21", features = ["full", "tracing"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = { version = "0.1" }
reqwest = { version = "0.11", features = ["json"] }

futures = "0.3"
tmq = { version = "0.3.2" }

tokio-serial = "5.4.4"

rumqttc = "0.17.0"

base64 = "0.13.0"
flate2 = {version = "1.0.17", features = ["zlib"]}

# [[example]]
# name = "chat"
# path = "chat.rs"
